### ISSUE TITLE
Information lost

### ISSUE THREAD

**Issue by reallyloudneighbours** [Payfast/mod-paid-memberships-pro#1]
This module loses registration information when added. I added the module as directed but when an user registers, the first and last name information is not inserted into the database. When I switch back to the original paid-memberships-pro.php file, the information is stored. I am using pmpro-add-name-to-checkout and pmpro-register-helper as well as I need more information from the user. All that entered information is lost when payfast is added to the paid-memberships-pro.php file.

**Comment by reallyloudneighbours** [comment]
It also causes the pmpro-pay-by-check module to give a 500 error when payfast is added. Without payfast module everything works 100% and no information is lost. With payfast module added and selected, information is lost and 500 error, page not found error is given when selecting pay by check.

**Comment by JGPage** [comment]
Apologies for the delay in responding.

We will have to investigate further though. Could you send your details to support@payfast.co.za and the issue will be dealt with by our technical team.
