### ISSUE TITLE
Clarify relationship to official plugin pmpro-payfast

### ISSUE THREAD

**Issue by cpbotha** [Payfast/mod-paid-memberships-pro#2]
What is the relationship of this fork to the payfast plugin created by the PaidMembershipsPro creator?

This one: https://github.com/strangerstudios/pmpro-payfast

Tangentially related to this: Was it really the best idea to hard fork the whole pmpro plugin? Much better would have been also writing a plugin, or, if that's really not possible for you, do a normal git fork which can easily be rebased off of upstream master to update with the latest fixes and improvements.

**Comment by RheinhardtSnyman** [comment]
The PayFast plugin created by Stranger Studios(pmpro-payfast) will in future replace paid-memberships-pro-1_8.

paid-memberships-pro-1_8 extends and overwrites vanilla PaidMembershipsPro base files to include PayFast.
paid-memberships-pro-1_8 has to be reinstalled when updating PaidMembershipsPro.
pmpro-payfast is an Add On of PaidMembershipsPro that is much simpler to install and maintain.

Please note that pmpro-payfast may allow for additional subscription settings that may not yet be functional. 
Currently PayFast only supports monthly and yearly subscriptions with PaidMembershipsPro.

If you have any more questions can you please submit your question to support@payfast.co.za

**Comment by cpbotha** [comment]
Baie dankie @RheinhardtSnyman !

**Comment by andrewlimaza** [comment]
Whoever still stumbles upon this issue, please see the latest version (free download) here - https://wordpress.org/plugins/pmpro-payfast/

**Comment by appinlet** [comment]
@cpbotha cc @andrewlimaza please note that v1.3.0 is the final release for this repository; mod-paid-memberships-pro is no longer supported and has been archived. 

We advise merchants to switch to the official plugin [Paid Memberships Pro – Payfast Gateway Add On](https://wordpress.org/plugins/pmpro-payfast/) by [Paid Memberships Pro](https://www.paidmembershipspro.com/).
